name: andresmontesinos
favicon: null
layout_spectrum: 0.002131545217707753
typography_spectrum: 0.39280300424434245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe5b6'
    - '#b1c296'
    - '#a56448'
    - '#050503'
    - '#b6906b'
  brandStrength: 0.03581101121380925
  lightness: 0.5301229304168373
  saturation: 0.08877402800135314
  rhythmicContrast: 0.49542553443461657
purpose: []
